//
//  CountryManager.swift
//  CountryPicker
//
//  Created by Samet Macit on 31.12.2020.
//  Copyright © 2021 Mobven. All rights reserved.

import Foundation
import UIKit

public final class CountryManager {
    public static let shared = CountryManager()
    private init() {}
    
    // Default theme is support dark mode
    public var config: Configuration = Config()
    
    // For localization we use current locale by default but you can change localeIdentifier for specific cases
    public var localeIdentifier: String = NSLocale.current.identifier
    
    /// - Returns: Country array
    public func getCountries() -> [Country] {

      return Countrys
    }
  
  let Countrys: [Country] = [
    Country(phoneCode: "93", isoCode: "AF"),
    Country(phoneCode: "355", isoCode: "AL"),
    Country(phoneCode: "213", isoCode: "DZ"),
    Country(phoneCode: "1", isoCode: "AS"),
    Country(phoneCode: "376", isoCode: "AD"),
    Country(phoneCode: "244", isoCode: "AO"),
    Country(phoneCode: "1", isoCode: "AI"),
    Country(phoneCode: "672", isoCode: "AQ"),
    Country(phoneCode: "1", isoCode: "AG"),
    Country(phoneCode: "54", isoCode: "AR"),
    Country(phoneCode: "374", isoCode: "AM"),
    Country(phoneCode: "297", isoCode: "AW"),
    Country(phoneCode: "61", isoCode: "AU"),
    Country(phoneCode: "43", isoCode: "AT"),
    Country(phoneCode: "994", isoCode: "AZ"),
    Country(phoneCode: "1", isoCode: "BS"),
    Country(phoneCode: "973", isoCode: "BH"),
    Country(phoneCode: "880", isoCode: "BD"),
    Country(phoneCode: "1", isoCode: "BB"),
    Country(phoneCode: "375", isoCode: "BY"),
    Country(phoneCode: "32", isoCode: "BE"),
    Country(phoneCode: "501", isoCode: "BZ"),
    Country(phoneCode: "229", isoCode: "BJ"),
    Country(phoneCode: "1", isoCode: "BM"),
    Country(phoneCode: "975", isoCode: "BT"),
    Country(phoneCode: "591", isoCode: "BO"),
    Country(phoneCode: "387", isoCode: "BA"),
    Country(phoneCode: "267", isoCode: "BW"),
    Country(phoneCode: "55", isoCode: "BR"),
    Country(phoneCode: "246", isoCode: "IO"),
    Country(phoneCode: "1", isoCode: "VG"),
    Country(phoneCode: "673", isoCode: "BN"),
    Country(phoneCode: "359", isoCode: "BG"),
    Country(phoneCode: "226", isoCode: "BF"),
    Country(phoneCode: "257", isoCode: "BI"),
    Country(phoneCode: "855", isoCode: "KH"),
    Country(phoneCode: "237", isoCode: "CM"),
    Country(phoneCode: "1", isoCode: "CA"),
    Country(phoneCode: "238", isoCode: "CV"),
    Country(phoneCode: "1", isoCode: "KY"),
    Country(phoneCode: "236", isoCode: "CF"),
    Country(phoneCode: "235", isoCode: "TD"),
    Country(phoneCode: "56", isoCode: "CL"),
    Country(phoneCode: "86", isoCode: "CN"),
    Country(phoneCode: "61", isoCode: "CX"),
    Country(phoneCode: "61", isoCode: "CC"),
    Country(phoneCode: "57", isoCode: "CO"),
    Country(phoneCode: "269", isoCode: "KM"),
    Country(phoneCode: "682", isoCode: "CK"),
    Country(phoneCode: "506", isoCode: "CR"),
    Country(phoneCode: "385", isoCode: "HR"),
    Country(phoneCode: "53", isoCode: "CU"),
    Country(phoneCode: "599", isoCode: "CW"),
    Country(phoneCode: "357", isoCode: "CY"),
    Country(phoneCode: "420", isoCode: "CZ"),
    Country(phoneCode: "243", isoCode: "CD"),
    Country(phoneCode: "45", isoCode: "DK"),
    Country(phoneCode: "253", isoCode: "DJ"),
    Country(phoneCode: "1", isoCode: "DM"),
    Country(phoneCode: "1", isoCode: "DO"),
    Country(phoneCode: "670", isoCode: "TL"),
    Country(phoneCode: "593", isoCode: "EC"),
    Country(phoneCode: "20", isoCode: "EG"),
    Country(phoneCode: "503", isoCode: "SV"),
    Country(phoneCode: "240", isoCode: "GQ"),
    Country(phoneCode: "291", isoCode: "ER"),
    Country(phoneCode: "372", isoCode: "EE"),
    Country(phoneCode: "251", isoCode: "ET"),
    Country(phoneCode: "500", isoCode: "FK"),
    Country(phoneCode: "298", isoCode: "FO"),
    Country(phoneCode: "679", isoCode: "FJ"),
    Country(phoneCode: "358", isoCode: "FI"),
    Country(phoneCode: "33", isoCode: "FR"),
    Country(phoneCode: "689", isoCode: "PF"),
    Country(phoneCode: "241", isoCode: "GA"),
    Country(phoneCode: "220", isoCode: "GM"),
    Country(phoneCode: "995", isoCode: "GE"),
    Country(phoneCode: "49", isoCode: "DE"),
    Country(phoneCode: "233", isoCode: "GH"),
    Country(phoneCode: "350", isoCode: "GI"),
    Country(phoneCode: "30", isoCode: "GR"),
    Country(phoneCode: "299", isoCode: "GL"),
    Country(phoneCode: "1", isoCode: "GD"),
    Country(phoneCode: "1", isoCode: "GU"),
    Country(phoneCode: "502", isoCode: "GT"),
    Country(phoneCode: "44", isoCode: "GG"),
    Country(phoneCode: "224", isoCode: "GN"),
    Country(phoneCode: "245", isoCode: "GW"),
    Country(phoneCode: "592", isoCode: "GY"),
    Country(phoneCode: "509", isoCode: "HT"),
    Country(phoneCode: "504", isoCode: "HN"),
    Country(phoneCode: "852", isoCode: "HK"),
    Country(phoneCode: "36", isoCode: "HU"),
    Country(phoneCode: "354", isoCode: "IS"),
    Country(phoneCode: "91", isoCode: "IN"),
    Country(phoneCode: "62", isoCode: "ID"),
    Country(phoneCode: "98", isoCode: "IR"),
    Country(phoneCode: "964", isoCode: "IQ"),
    Country(phoneCode: "353", isoCode: "IE"),
    Country(phoneCode: "44", isoCode: "IM"),
    Country(phoneCode: "972", isoCode: "IL"),
    Country(phoneCode: "39", isoCode: "IT"),
    Country(phoneCode: "225", isoCode: "CI"),
    Country(phoneCode: "1", isoCode: "JM"),
    Country(phoneCode: "81", isoCode: "JP"),
    Country(phoneCode: "44", isoCode: "JE"),
    Country(phoneCode: "962", isoCode: "JO"),
    Country(phoneCode: "7", isoCode: "KZ"),
    Country(phoneCode: "254", isoCode: "KE"),
    Country(phoneCode: "686", isoCode: "KI"),
    Country(phoneCode: "383", isoCode: "XK"),
    Country(phoneCode: "965", isoCode: "KW"),
    Country(phoneCode: "996", isoCode: "KG"),
    Country(phoneCode: "856", isoCode: "LA"),
    Country(phoneCode: "371", isoCode: "LV"),
    Country(phoneCode: "961", isoCode: "LB"),
    Country(phoneCode: "266", isoCode: "LS"),
    Country(phoneCode: "231", isoCode: "LR"),
    Country(phoneCode: "218", isoCode: "LY"),
    Country(phoneCode: "423", isoCode: "LI"),
    Country(phoneCode: "370", isoCode: "LT"),
    Country(phoneCode: "352", isoCode: "LU"),
    Country(phoneCode: "853", isoCode: "MO"),
    Country(phoneCode: "389", isoCode: "MK"),
    Country(phoneCode: "261", isoCode: "MG"),
    Country(phoneCode: "265", isoCode: "MW"),
    Country(phoneCode: "60", isoCode: "MY"),
    Country(phoneCode: "960", isoCode: "MV"),
    Country(phoneCode: "223", isoCode: "ML"),
    Country(phoneCode: "356", isoCode: "MT"),
    Country(phoneCode: "692", isoCode: "MH"),
    Country(phoneCode: "222", isoCode: "MR"),
    Country(phoneCode: "230", isoCode: "MU"),
    Country(phoneCode: "262", isoCode: "YT"),
    Country(phoneCode: "52", isoCode: "MX"),
    Country(phoneCode: "691", isoCode: "FM"),
    Country(phoneCode: "373", isoCode: "MD"),
    Country(phoneCode: "377", isoCode: "MC"),
    Country(phoneCode: "976", isoCode: "MN"),
    Country(phoneCode: "382", isoCode: "ME"),
    Country(phoneCode: "1", isoCode: "MS"),
    Country(phoneCode: "212", isoCode: "MA"),
    Country(phoneCode: "258", isoCode: "MZ"),
    Country(phoneCode: "95", isoCode: "MM"),
    Country(phoneCode: "264", isoCode: "NA"),
    Country(phoneCode: "674", isoCode: "NR"),
    Country(phoneCode: "977", isoCode: "NP"),
    Country(phoneCode: "31", isoCode: "NL"),
    Country(phoneCode: "599", isoCode: "AN"),
    Country(phoneCode: "687", isoCode: "NC"),
    Country(phoneCode: "64", isoCode: "NZ"),
    Country(phoneCode: "505", isoCode: "NI"),
    Country(phoneCode: "227", isoCode: "NE"),
    Country(phoneCode: "234", isoCode: "NG"),
    Country(phoneCode: "683", isoCode: "NU"),
    Country(phoneCode: "850", isoCode: "KP"),
    Country(phoneCode: "1", isoCode: "MP"),
    Country(phoneCode: "47", isoCode: "NO"),
    Country(phoneCode: "968", isoCode: "OM"),
    Country(phoneCode: "92", isoCode: "PK"),
    Country(phoneCode: "680", isoCode: "PW"),
    Country(phoneCode: "970", isoCode: "PS"),
    Country(phoneCode: "507", isoCode: "PA"),
    Country(phoneCode: "675", isoCode: "PG"),
    Country(phoneCode: "595", isoCode: "PY"),
    Country(phoneCode: "51", isoCode: "PE"),
    Country(phoneCode: "63", isoCode: "PH"),
    Country(phoneCode: "64", isoCode: "PN"),
    Country(phoneCode: "48", isoCode: "PL"),
    Country(phoneCode: "351", isoCode: "PT"),
    Country(phoneCode: "1", isoCode: "PR"),
    Country(phoneCode: "974", isoCode: "QA"),
    Country(phoneCode: "242", isoCode: "CG"),
    Country(phoneCode: "262", isoCode: "RE"),
    Country(phoneCode: "40", isoCode: "RO"),
    Country(phoneCode: "7", isoCode: "RU"),
    Country(phoneCode: "250", isoCode: "RW"),
    Country(phoneCode: "590", isoCode: "BL"),
    Country(phoneCode: "290", isoCode: "SH"),
    Country(phoneCode: "1", isoCode: "KN"),
    Country(phoneCode: "1", isoCode: "LC"),
    Country(phoneCode: "590", isoCode: "MF"),
    Country(phoneCode: "508", isoCode: "PM"),
    Country(phoneCode: "1", isoCode: "VC"),
    Country(phoneCode: "685", isoCode: "WS"),
    Country(phoneCode: "378", isoCode: "SM"),
    Country(phoneCode: "239", isoCode: "ST"),
    Country(phoneCode: "966", isoCode: "SA"),
    Country(phoneCode: "221", isoCode: "SN"),
    Country(phoneCode: "381", isoCode: "RS"),
    Country(phoneCode: "248", isoCode: "SC"),
    Country(phoneCode: "232", isoCode: "SL"),
    Country(phoneCode: "65", isoCode: "SG"),
    Country(phoneCode: "1", isoCode: "SX"),
    Country(phoneCode: "421", isoCode: "SK"),
    Country(phoneCode: "386", isoCode: "SI"),
    Country(phoneCode: "677", isoCode: "SB"),
    Country(phoneCode: "252", isoCode: "SO"),
    Country(phoneCode: "27", isoCode: "ZA"),
    Country(phoneCode: "82", isoCode: "KR"),
    Country(phoneCode: "211", isoCode: "SS"),
    Country(phoneCode: "34", isoCode: "ES"),
    Country(phoneCode: "94", isoCode: "LK"),
    Country(phoneCode: "249", isoCode: "SD"),
    Country(phoneCode: "597", isoCode: "SR"),
    Country(phoneCode: "47", isoCode: "SJ"),
    Country(phoneCode: "268", isoCode: "SZ"),
    Country(phoneCode: "46", isoCode: "SE"),
    Country(phoneCode: "41", isoCode: "CH"),
    Country(phoneCode: "963", isoCode: "SY"),
    Country(phoneCode: "886", isoCode: "TW"),
    Country(phoneCode: "992", isoCode: "TJ"),
    Country(phoneCode: "255", isoCode: "TZ"),
    Country(phoneCode: "66", isoCode: "TH"),
    Country(phoneCode: "228", isoCode: "TG"),
    Country(phoneCode: "690", isoCode: "TK"),
    Country(phoneCode: "676", isoCode: "TO"),
    Country(phoneCode: "1", isoCode: "TT"),
    Country(phoneCode: "216", isoCode: "TN"),
    Country(phoneCode: "90", isoCode: "TR"),
    Country(phoneCode: "993", isoCode: "TM"),
    Country(phoneCode: "1", isoCode: "TC"),
    Country(phoneCode: "688", isoCode: "TV"),
    Country(phoneCode: "1", isoCode: "VI"),
    Country(phoneCode: "256", isoCode: "UG"),
    Country(phoneCode: "380", isoCode: "UA"),
    Country(phoneCode: "971", isoCode: "AE"),
    Country(phoneCode: "44", isoCode: "GB"),
    Country(phoneCode: "1", isoCode: "US"),
    Country(phoneCode: "598", isoCode: "UY"),
    Country(phoneCode: "998", isoCode: "UZ"),
    Country(phoneCode: "678", isoCode: "VU"),
    Country(phoneCode: "379", isoCode: "VA"),
    Country(phoneCode: "58", isoCode: "VE"),
    Country(phoneCode: "84", isoCode: "VN"),
    Country(phoneCode: "681", isoCode: "WF"),
    Country(phoneCode: "212", isoCode: "EH"),
    Country(phoneCode: "967", isoCode: "YE"),
    Country(phoneCode: "260", isoCode: "ZM"),
    Country(phoneCode: "263", isoCode: "ZW")
  ]

}
